move into deploy

diff --git a/.github/workflows/python-package.yml b/.github/workflows/python-package.yml
--- a/.github/workflows/python-package.yml
+++ b/.github/workflows/python-package.yml
@@ -10,19 +10,6 @@ on:
   merge_group:
 
 jobs:
-  deployment-window:
-    runs-on: ubuntu-latest
-    if: github.event_name == 'push'
-    steps:
-    - name: Check Deployment Window
-      run: |
-        TZ='America/Toronto' date +%H
-        current_hour=$(TZ='America/Toronto' date +%H)
-        if [ "$current_hour" -lt 7 ] || [ "$current_hour" -ge 22 ]; then
-          echo "::error::Deployments are disabled between 10pm and 7am"
-          exit 1
-        fi
-
   test:
     runs-on: ubuntu-latest
     steps:
@@ -75,7 +62,6 @@ jobs:
 
   deploy:
     needs:
-    - deployment-window
     - test
     - sanity
     - synthesize
@@ -84,6 +70,14 @@ jobs:
     concurrency: deploy
     environment: prod
     steps:
+    - name: Check Deployment Window
+      run: |
+        TZ='America/Toronto' date +%H
+        current_hour=$(TZ='America/Toronto' date +%H)
+        if [ "$current_hour" -lt 7 ] || [ "$current_hour" -ge 22 ]; then
+          echo "::error::Deployments are disabled between 10pm and 7am. Retry later."
+          exit 1
+        fi
     - uses: actions/checkout@v6
     - name: Build and Push Docker Image
       id: image
