🚀 avoid deployments overnight (#1244)

diff --git a/.github/workflows/python-package.yml b/.github/workflows/python-package.yml
--- a/.github/workflows/python-package.yml
+++ b/.github/workflows/python-package.yml
@@ -70,6 +70,14 @@ jobs:
     concurrency: deploy
     environment: prod
     steps:
+    - name: Check Deployment Window
+      run: |
+        TZ='America/Toronto' date +%H
+        current_hour=$(TZ='America/Toronto' date +%H)
+        if [ "$current_hour" -lt 7 ] || [ "$current_hour" -ge 22 ]; then
+          echo "::error::Deployments are disabled between 10pm and 7am. Retry later."
+          exit 1
+        fi
     - uses: actions/checkout@v6
     - name: Build and Push Docker Image
       id: image
